services:
  - type: web
    name: neuronerds-quiz-backend
    runtime: node
    plan: free
    buildCommand: |
      rm -rf node_modules package-lock.json
      npm install --legacy-peer-deps
      npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000